# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='transcription_service.proto',
    package='transcription',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1btranscription_service.proto\x12\rtranscription\"&\n\x13VoiceMessageRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"%\n\x15TranscriptionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2z\n\x14TranscriptionService\x12\x62\n\x16TranscribeVoiceMessage\x12\".transcription.VoiceMessageRequest\x1a$.transcription.TranscriptionResponseb\x06proto3'
)


_VOICEMESSAGEREQUEST = _descriptor.Descriptor(
    name='VoiceMessageRequest',
    full_name='transcription.VoiceMessageRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='file_id', full_name='transcription.VoiceMessageRequest.file_id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=46,
    serialized_end=84,
)


_TRANSCRIPTIONRESPONSE = _descriptor.Descriptor(
    name='TranscriptionResponse',
    full_name='transcription.TranscriptionResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='text', full_name='transcription.TranscriptionResponse.text', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=86,
    serialized_end=123,
)

DESCRIPTOR.message_types_by_name['VoiceMessageRequest'] = _VOICEMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['TranscriptionResponse'] = _TRANSCRIPTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoiceMessageRequest = _reflection.GeneratedProtocolMessageType('VoiceMessageRequest', (_message.Message,), {
    'DESCRIPTOR': _VOICEMESSAGEREQUEST,
    '__module__': 'transcription_service_pb2'
    # @@protoc_insertion_point(class_scope:transcription.VoiceMessageRequest)
})
_sym_db.RegisterMessage(VoiceMessageRequest)

TranscriptionResponse = _reflection.GeneratedProtocolMessageType('TranscriptionResponse', (_message.Message,), {
    'DESCRIPTOR': _TRANSCRIPTIONRESPONSE,
    '__module__': 'transcription_service_pb2'
    # @@protoc_insertion_point(class_scope:transcription.TranscriptionResponse)
})
_sym_db.RegisterMessage(TranscriptionResponse)


_TRANSCRIPTIONSERVICE = _descriptor.ServiceDescriptor(
    name='TranscriptionService',
    full_name='transcription.TranscriptionService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=125,
    serialized_end=247,
    methods=[
        _descriptor.MethodDescriptor(
            name='TranscribeVoiceMessage',
            full_name='transcription.TranscriptionService.TranscribeVoiceMessage',
            index=0,
            containing_service=None,
            input_type=_VOICEMESSAGEREQUEST,
            output_type=_TRANSCRIPTIONRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_TRANSCRIPTIONSERVICE)

DESCRIPTOR.services_by_name['TranscriptionService'] = _TRANSCRIPTIONSERVICE

# @@protoc_insertion_point(module_scope)
